# Generated by Django 3.2.13 on 2023-07-29 09:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_advertisements', '0007_auto_20230729_1232'),
    ]

    operations = [
    ]
