# Generated by Django 3.2.13 on 2023-07-29 08:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_advertisements', '0003_alter_advertisement_auction'),
    ]

    operations = [
    ]
